package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"connectrpc.com/connect"

	"reamde.dev/monolith/proto/example"                // generated by protoc-gen-go
	"reamde.dev/monolith/proto/example/exampleconnect" // generated by protoc-gen-connect-go
)

func main() {
	client := exampleconnect.NewStringsServiceClient(
		http.DefaultClient,
		"http://localhost:8080",
	)
	res, err := client.Upper(
		context.Background(),
		connect.NewRequest(
			&example.UpperRequest{
				Value: "Jane",
			},
		),
	)
	if err != nil {
		log.Fatal(fmt.Errorf("failed to call Upper: %w", err))
	}
	log.Println(res.Msg.Value)
}
