// Code generated by protoc-gen-go-ascii. DO NOT EDIT.

package monolith

func (x *PublicKey) Ascii() string {
	return `hello`
}
func (x *PrivateKey) Ascii() string {
	return `hello`
}
func (x *Identity) Ascii() string {
	return `hello`
}
func (x *Address) Ascii() string {
	return `hello`
}
func (x *PeerInfo) Ascii() string {
	return `hello`
}
func (x *BrokerInfo) Ascii() string {
	return `hello`
}
func (x *ProviderInfo) Ascii() string {
	return `hello`
}
func (x *AccountInfo) Ascii() string {
	return `hello`
}
